### ISSUE TITLE
Make problem folder in pwd instead of home directory

### ISSUE THREAD

**Issue by Abhishek-dev2** [kp96/nodeforces#33]
It is very odd for me that I need to set advanced configuration to change the location for new-folder-creation-location. I think that it should always be current folder unless specified by a flag.

Hope you understand.

**Comment by kp96** [comment]
Makes sense. The reason I chose to specify a directory is not to pollute a non empty directory with folders and text files.

**Comment by Abhishek-dev2** [comment]
Yes, I understand. I will try to add this feature to do it in pwd.

**Comment by kp96** [comment]
Great.

**Comment by kp96** [comment]
Doing this by default makes sense. We will do it in #34
